version: "3.8"

services:
  app:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "80:5000"
    environment:
      - PORT=80
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://0.0.0.0:5000/api/v1/utils/healthchecker" ]
      interval: 10s
      retries: 5
      timeout: 5s

  db:
    image: postgres:17
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
      timeout: 3s
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  postgres_data: